all:clean lexcmp lencmp digcmp loopcmp	nicecmp

prog1:
	gcc -o lexcmp lexcmp.c -Wall
prog2:
	gcc -o lencmp lencmp.c -Wall
prog3:	
	gcc -o  digcmp digcmp.c -Wall
prog4:
	gcc -o loopcmp loopcmp.c -Wall	
prog5:		
	gcc	-o	nicecmp	nicecmp.c	-Wall		
clean: 	
	rm -f lexcmp.o lexcmp
	rm -f lencmp.o lencmp
	rm -f digcmp.o digcmp
	rm -f loopcmp.o loopcmp		
	rm	-f	nicecmp.o	nicecmp
